[project]
name = "leaguelivepersonaltrainer"
version = "0.1.0"
description = "League Live Personal Trainer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.0",
    "requests>=2.32.5",
]
